### ISSUE TITLE
TypeCache should move to the SF package

### ISSUE THREAD

**Issue by FejZa** [realitycollective/com.realitycollective.utilities#49]
# Reality Collective - Utilities Bug Report

## Describe the bug

The TypeCache should move to the SF package as it is 100% tied to it. I can't come up with a single situation where anyone
just wanting a Utilities package would have any use of the TypeCache class. Its single purpose is to manage the SF types.

**Comment by SimonDarksideJ** [comment]
Agreed, will move today
